version: 2

sources:
  - name: retailiq_raw
    project: retailiq-analytics-508120
    dataset: retailiq_raw
    tables:
      - name: raw_sales
      - name: raw_products
      - name: raw_stores
      - name: raw_inventory